### ISSUE TITLE
Pressable onHover, onMouseDown, onMouseUp callback

### ISSUE THREAD

**Issue by VladimirCores** [fluttertools/mix#66]
Hello `mix` team. Is there any way how to detect `onHover`, `onMouseDown`, `onMouseUp` from Pressable? I need to highlight specific a range of cells in a grid, starting from the one over which user has pressed mouse down and end on another where mouse up.
 
![Screenshot_select-area_20220321174135](https://user-images.githubusercontent.com/442111/159285752-3923fe91-90fd-489d-8f5d-e1a434105d0b.jpg)

**Comment by bdlukaa** [comment]
Hello! You can make use of the `MouseRegion` widget for the `onHover` callback:

```dart
MouseRegion(
  onHover: (event) {},
  child: Pressable(...),
),
```

For the `onMouseUp` and `onMouseDown`, you can make use of `GestureDetector`:

```dart
GestureDetector(
  onTapUp: (d) {},
  onTapDown: (d) {},
  child: MouseRegion(...),
),
```

I don't like the idea of adding more callbacks to `Pressable`. @leoafarias what do you think of adding gesture attributes, like:

```dart
final mix = Mix(
  onPressed(() {
    print('pressed');
  }),
  onEnterHover(() {
    print('entered hover');
  }),
);
```

**Comment by leoafarias** [comment]
Not a fan of adding too much behavioral and business logic into mix... let's close the flow on the style and visual piece and get some feedback

**Comment by VladimirCores** [comment]
We use `MouseRegion`, thanks all for suggestions ;)
